### PR TITLE
Adding Learning Lab Documentation

### LINKED ISSUE #26: Documentation needed for Learning Lab
Documentation for working with learning labs is needed, specifically for the `config.yml` files.

### PR DESCRIPTION
**Pull request by emsesc**
Previously, the BitCamp repo did not have documentation for Github Learning Labs that allows for easy development of labs without the UI. `Learning-Labs101.md` includes instructions for the config.yml file needed for Github Learning Labs. @lazyplatypus @shreythecray

### CODE REVIEW

**Comment by emsesc** [comment]
Would appreciate feedback on clarity/any missing components that developers of learning labs would need to know.

**Review by lazyplatypus — CHANGES_REQUESTED** [review]
I think it would benefit with two minor changes. 

- Add links to relevant documentation and the learning lab (https://lab.github.com/githubtraining/write-a-learning-lab-course) under a "resources" section at the very bottom/top. 
- Perhaps go into what the config.yml file does (copy and paste +cite the documentation)

**Comment by emsesc** [comment]
@lazyplatypus I applied your requested changes and added more content/documentation regarding the general development of Github Learning Labs (for the Eduflow course). There's now a directory called "Learning-Labs-101."

**Comment by beaubhp** [comment]
Looks good, @lazyplatypus had good suggestions. One thing I might add is further explaining the "steps" part by going into detail. For example, maybe add a few small sections on the steps attributes (ex: actions, events, etc). I get that you point towards documentation but it might help to give a quick and helpful overview. What do you think @lazyplatypus @emsesc?

**Review by beaubhp — APPROVED** [review]
Other than my first suggestion, everything looks great! I'll be sure to add my part tomorrow. Great job @emsesc!

**Comment by emsesc** [comment]
> Looks good, @lazyplatypus had good suggestions. One thing I might add is further explaining the "steps" part by going into detail. For example, maybe add a few small sections on the steps attributes (ex: actions, events, etc). I get that you point towards documentation but it might help to give a quick and helpful overview. What do you think @lazyplatypus @emsesc?

I agree with this suggestion, the Github docs go into unnecessary detail at some points. I added more detailed explanations for each attribute!

**Comment by beaubhp** [comment]
Just saw. Looks great! Thoughts @lazyplatypus?

**Review by lazyplatypus — APPROVED** [review]
Great job <3

**Pull request merged**
