### PR TITLE
Update 2.2.1-checkpoint1.md

### LINKED ISSUE #128: [BUG] Week 1 of Intro to Serverless Issue #2 Instructions Unclear
**Describe the bug**

After creating the js file, there are no instructions to run the file or anything to commit.

Also, we should have more instructions on how to install node and other technologies in case students are super new to coding and don't have them pre-installed.

Also also, we need to include a link to the bitcamp repo in case people want to make suggestions for improvement (open isssues)

Also also also, clarify how to move onto next issue (comment vs comment and close)

**Context**
Issue 2 in week 1 of Intro to Serverless

**Desired Outcome**

More instructions in issue

### LINKED ISSUE #129: [BUG] Intro to Serverless Checkpoint 1 Instructions Unclear
**Describe the bug**

I think in general the learning lab is written really well but it's missing some instructions that can make it difficult for students who are doing the lab on their own. 

In Checkpoint 1, we need more instructions on how to setup Postman and get started (the gif showed it all but was low res and the stuff happening in the gifs should be described more clearly in text).

"When you hit send to send the request, make sure to have your Function open in another tab to observe what happens. You should get something like this:" --> where are we seeing this? Need gifs and documentation.

### LINKED ISSUE #130: [BUG] Create a Face API Endpoint
**Describe the bug**

Not sure what to save when it says "Record and save the API endpoint and subscription key, as we'll be using it in the following parts."

**Context**

Learning lab issue 2 Create a Face API Endpoint

**Desired Outcome**

Clarification, perhaps with screenshots

### PR DESCRIPTION
**Pull request by shreythecray**
Added some descriptions about how to use Postman (to explain the gifs).

### CODE REVIEW

**Comment by shreythecray** [comment]
Added descriptions on how to write js file hello, world in case they had not viewed the live lecture or they were not familiar with js.

**Comment by shreythecray** [comment]
Added descriptions on how to get keys and endpoint for face API and screenshots.

**Review by TheDirector23 — COMMENTED** [review]
looks good - the screenshots and extra info will be very helpful for the students who are doing it by themselves or those who are more beginners

**Review by evcyen — COMMENTED** [review]
this is perfect! great to have a new set of eyes on these - I've looked at my blogs so often that I can't keep my head straight lol - thanks so much Shreya!

**Review by emsesc — APPROVED** [review]
A lot more readable and beginner friendly! The visuals help a lot 👍

**Pull request merged**
