### PR TITLE
Adding Blogs for Serverless Livestreams

### LINKED ISSUE #43: Livestream Blogs for Serverless Camp
**Is your proposal related to a problem?**

After livestreams, students don't have a place where they can reference all the code and content that was covered.

**Describe the solution you'd like**

Providing students with livestream blogs give them a place where they can quickly review the steps taken without needing to skip through the video. Blogs would include code snippets and any other needed instructions.

**Describe alternatives you've considered**

None.

**Additional context**

None.

### PR DESCRIPTION
**Pull request by emsesc**
Since students do not have easy access to what content/code was covered in livestreams, a blog will help centralize information and allow for simple reference.

### CODE REVIEW

**Comment by lazyplatypus** [comment]
is this just for week 3? if so we need to rename the issue. Also, can we add the summary to part of the learning lab?

**Comment by emsesc** [comment]
> is this just for week 3? if so we need to rename the issue. Also, can we add the summary to part of the learning lab?

@lazyplatypus Week 2 was merged earlier this month. All that's left is Week 1 - would you prefer the weeks to be separate PR's? What summary are you referring to?

**Comment by lazyplatypus** [comment]
Oh mb, that sounds great! Then disregard my comment. I misspoke, can we have the markdown file (the blog) as a step after the students give feedback on the live stream? I think it will reinforce the students' knowledge. Or we could have it part of the bit project blog and have students be redirected to that page.

**Comment by emsesc** [comment]
@lazyplatypus I like the idea of having it in the learning lab

**Pull request merged**
