### PR TITLE
Week 4 and 5 Material (UI)

### LINKED ISSUE #48: [Feature Request] Implement Weeks 4 and 5 of GameDev BitCamp
**Is your proposal related to a problem?**

Updating the GameDev curriculum

**Describe the solution you'd like**

Upload Weeks 4 and 5 of the GameDev Curriculum

**Additional context**

Weeks 4 and 5 of 7, as part of BitCamp GameDev.

### PR DESCRIPTION
**Pull request by HeadlessKhan**
Fixes #48

### CODE REVIEW

**Comment by HeadlessKhan** [comment]
Just a note, the main tutorial solution is in week 5 because we finish going over it in that week so there are no solutions in week 4. Furthermore, there is starter code and solution code for an inventory system that serves as a second UI example that we go over in week 5.

**Comment by lazyplatypus** [comment]
@emsesc what do you think about the formatting?

**Comment by emsesc** [comment]
First off, I see some committed .ds_store files - might need to remove those @lazyplatypus is that right? 

Some parts might be more clear with more explanation. Ex: [this file](https://github.com/HeadlessKhan/BitCamp/blob/master/GameDev/week5/homework/issues/MainMenuAndInventory.md) might benefit from some more details. As for the "issues" directory, this should include more of a walkthrough than just code solutions. @HeadlessKhan check out [Slack Apps](https://github.com/bitprj/BitCamp/tree/master/Slack-Apps) to see what that looks like.

I would recommend removing the PDF live stream scripts and adding the pictures into the md file.

Other than that, the code is well organized and the live stream scripts are nicely formatted! Just fix up the structure a little and refer to Slack Apps as an example.

**Comment by lazyplatypus** [comment]
yeap @HeadlessKhan here is the link on how you do that :) 
https://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository

**Comment by HeadlessKhan** [comment]
I've removed the ds_store files, updates the descriptions for a couple of files, and embedded the code snippet images into the scripts.  

Regarding the "issues" directory comment, I think I may have misinterpreted the directions for where everything needs to go. I thought that all starter code and code solutions are meant to go into the homework folder even if they aren't actually "homework." Everything we are coving and all the code students are writing are meant to be done during the lesson itself, so we don't have any actual homework. Therefore, should I move all of that content over into the livestream directory and leave homework empty?

**Comment by emsesc** [comment]
@HeadlessKhan The livestream files look much better, and thanks for removing the ds_store files! @lazyplatypus and I are changing the directory structure, so the homework folder will contain a Learning Lab. I would say hold off on moving files for now. Are you guys creating a "Github Learning Lab" for the students to complete, or will all the instruction be during livestreams?

**Comment by HeadlessKhan** [comment]
All of the instructions will be in the livestream. The idea is for the students to be able to code along with us and finish the projects we work on by the end of the livestreams.

**Comment by emsesc** [comment]
@lazyplatypus If game dev won't have a learning lab, how should we structure the repo?

**Comment by HeadlessKhan** [comment]
@lazyplatypus @emsesc Are there any changes I should be making at this time or should I just wait for one of you to approve the pull request?

**Review by emsesc — APPROVED** [review]
@HeadlessKhan everything looks great!

**Pull request merged**
