### PR TITLE
Improve Documentation of Bitcamp Curriculum

### LINKED ISSUE #1: Improve documentation of the serverless curriculum
Currently, the README.md files for each of the weeks, as well as the one for the main repository does not provide enough context. Please add gifs/screenshots of the projects, more detailed descriptions, and links to videos (if exists).

### PR DESCRIPTION
**Pull request by emsesc**
Added short summaries and gifs to clarify for those who want to contribute. Aims to establish clear goals of the entire camp and each week.

### CODE REVIEW

**Comment by lazyplatypus** [comment]
I think this is really interesting way to format the information. @Bahburs comments requested.

**Comment by beaubhp** [comment]
I will review it tonight, however, I like the new formatting style @Bahburs

**Review by beaubhp — COMMENTED** [review]
Pre-requisite section is good but I think adding a few resources/links might be helpful. If we are opening the curriculum up to the public we should add a bit more direction for getting into JS, etc.

**Review by beaubhp — COMMENTED** [review]
👍

**Review by beaubhp — COMMENTED** [review]
Removing Week 4 changes on purpose? I haven't been up to date on where the curriculum is going for Serverless, has it changed?

**Review by beaubhp — COMMENTED** [review]
This isn't needed but maybe at the end of each week MDs we could add a section on how the livestream connects to the homework? This might help open-source users.

**Comment by beaubhp** [comment]
Overall: I think the changes look great, the curriculum is much more in detail and the flow is much smoother. One thing is I'm not up to date on the actual code content so some of the changes (ex: valence, week 4, etc) are a bit confusing to me. I think a possibility, this doesn't have to be done, but it might help if we add a short part on the transition from livestream to homework? Other than that, updated content looks great @emsesc @lazyplatypus

**Pull request merged**
